# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os tutores
- Divirta-se :)

### 01 - Teste de gravidez
Escreva uma célula com controle de fluxos que tem como premissa a existência das seguintes variáveis:

- ```sexo``` como ```str``` indicando os valores '**M**' para masculino e '**F**' para feminino  
- ```beta_hcg``` que indica a quantidade do beta-HCG no sangue em mUI/mL.

A sua tarefa é escrever um código que imprima como resultado "indivíduo do sexo masculino" quando sexo = 'M', caso sexo = 'F', se o valor de beta-HCG for maior que 5, retorne "Positivo" indicando que a paciente está grávida, e retorne "Negativo" caso contrário.

Não mexa nos valores da variável ```sexo``` nem em ```beta_hcg```, e escreva um código que funcione para quaisquer valores possíveis de ambos: ```sexo``` = '**M**' ou '**F**' e ```beta_hcg``` assumindo valores inteiros positivos.

In [16]:
sexo = 'M'
beta_hcg = 0

# seu código vem abaixo desta linha
if sexo == 'F' and beta_hcg > 5:
    print('Parabéns você está grávida. WoW!')
elif sexo == 'F' and beta_hcg < 5:
    print('Ainda não foi dessa vez. Vamos continuar tentando, não desista!')
elif sexo == 'M':
    print('Bem, você é do sexo masculino. A ciência não evoluiu tanto assim. Você ainda não pode engravidar, quem sabe em breve!')
else:
    print('Não consigo responter esta :(. A opção sexo deve está definida com (M) Masculino ou (F) Feminino.')


Bem, você é do sexo masculino. A ciência não evoluiu tanto assim. Você ainda não pode engravidar, quem sabe em breve!


### 02 - Renomeando variáveis

Vamos ver adiante que uma forma de renomear variáveis de um conjunto de dados é através de dicionários - o dicionário deve conter como chave o nome original, associando a cada chave um único valor (tipo *str*) que contenha o nome novo.

A sua tarefa é escrever um dicionário que possa ser utilizado para traduzir as variáveis ```name``` (nome), ```age``` (idade) e ```income``` (renda). Ou seja, esse dicionário deve relacionar as chaves *name, age* e *income* às suas respectivas traduções.

In [52]:
dic_renomeacao = {
                    'hudson': {
                        'name':'Hudson',
                         'age': 47,
                         'income': 10000.00
                    },
                    'lucas': {
                        'name':'Lucas',
                        'age': 45,
                        'income': 20000.00
                    },                    
                 }

print (f'Apresentando todo o dicionário {dic_renomeacao}')

income_hudson = dic_renomeacao['hudson']['income']

print (f'Acessando o income do hudson {income_hudson}')



Apresentando todo o dicionário {'hudson': {'name': 'Hudson', 'age': 47, 'income': 10000.0}, 'lucas': {'name': 'Lucas', 'age': 45, 'income': 20000.0}}
Acessando o income do hudson 10000.0


### 03 - É divisível?
A sua tarefa é escrever um código que indique se um número ```N``` é divisível por um número P. Escreva um programa que faça essa verificação para quaisquer combinações de ```N``` e ```M``` e devolva uma mensagem indicativa no output.

In [82]:
N = 42
M = 7

#Seu código
if M == 0 : 
    print(f'O denominador da divisão não pode ser igual a {M}')
elif N % M == 0 :
    print(f'O número {N} é divisível por {M}')
else:
    print(f'O número {N} NÃO é divisível por {M}')
          


O número 42 é divisível por 7


### 04 - Números primos
> Um número **N** é primo se e somente se é divisível por 1, -1, por **N** e por -**N**.  

Escreva um script que verifica se ```N``` é um número primo, verificando se ```N``` é divisível por todos os números de ```1``` a ```N-1```. Você vai precisar usar alguma ferramenta de *loop* que você aprendeu para isto. No final, devolva uma mensagem no output indicando se o número é primo ou não.

In [110]:
N = 47


# seu código abaixo

naoPrimo = 0

for i in range(2,N):
    if (N % i == 0):
        naoPrimo += 1
        
if (naoPrimo == 0):
    print(f'O número {N} é primo.')
else:
    print(f'O número {N} NÂO é primo.')
    


O número 47 é primo.


### 05 - Desafio
O algorítmo do exercício anterior não é o mais eficiente. O que você pode fazer para deixá-lo mais eficiente? Ou seja, executar menos comparações, portanto consumir menos tempo.
1. Será que precisamos correr o loop até o final sempre?
2. Será que precisamos mesmo verificar **todos** os números?
3. Será que precisamos ir até N-1?

Essas perguntas levam ao tipo de pensamento voltado a deixar um algoritmo mais eficiente. Veja se você consegue melhorar o seu.

In [132]:
N = 98

# seu código aqui

#lista criada para verificar a eficiencia do comando break
#listaPrimo = []

naoPrimo = 0

for i in range(2,N):
    #listaPrimo.append(i)
    if (N % i == 0):
        naoPrimo += 1
        break
        
if (naoPrimo == 0):
    print(f'O número {N} é primo.')
else:
    print(f'O número {N} NÂO é primo.')
    
#print (f'Números percorridos para verificar se é primo {listaPrimo}')

O número 98 NÂO é primo.


### 06 - Peso ideal 1
O IMC (índice de massa corpórea) é um indicador de saúde mais bem aceito que o peso. Ele é calculado como:

$$ IMC = \dfrac{peso}{altura^2}$$

Segundo a OMS, valores *normais* são entre 18.5 e 24.9.

Sua tarefa é encontrar o ponto médio dessa faixa.

In [162]:
meusNumeros = [18.5,24.9]
imc_ideal = sum(meusNumeros)/len(meusNumeros)
print (f' O ponto médio entre {meusNumeros[0]} m e {meusNumeros[1]} é {imc_ideal}.')

 O ponto médio entre 18.5 m e 24.9 é 21.7.


)### 07 - Peso ideal 2
Recebendo um valor de altura, encontre o peso '*ideal*' dessa pessoa, que fornece o IMC encontrado acima

In [169]:
altura = 1.70

# Seu código
peso_ideal = imc_ideal * (altura**2)
print(f'O peso_ideal para a pessoa que tem a altura de {altura:.2f} m e o imc de {imc_ideal:.1f} é de {peso_ideal:.2f}.')


O peso_ideal para a pessoa que tem a altura de 1.70 m e o imc de 21.7 é de 62.71.


### 08 - Peso ideal 3
Dada uma lista contendo as alturas de pacientes, crie uma nova lista que contenha o peso '*ideal*' (que fornece o IMC calculado em **Peso ideal 1**) desses pacientes.

In [170]:
lista_alturas = [1.95, 2.05, 1.70, 1.65]

lista_peso_ideal = []

# seu código
for i in lista_alturas:
    lista_peso_ideal.append(imc_ideal * (i**2))

lista_peso_ideal

[82.51424999999999, 91.19425, 62.712999999999994, 59.07824999999999]

### 09 - Peso ideal 4
Dada uma lista de tuplas - cada elemento da lista é uma tupla contendo altura e peso de um paciente - crie uma nova lista com o IMC desses pacientes.

In [192]:
altura_peso = [(1.80, 90), (1.65, 75), (1.91, 70)]

imc = []

# seu código
for i in altura_peso:
    imc.append(i[1]/(i[0]**2))

imc

[27.777777777777775, 27.548209366391188, 19.188070502453332]

### 10 - Peso ideal 5
Dada uma lista de **listas** - cada elemento da lista é uma **lista** contendo altura e peso de um paciente, adicione mais um elemento à lista de cada paciente contendo o IMC do paciente. Verifique também se é 'baixo', 'normal' ou 'alto' segundo os padrões da OMS em que normal é entre 18.5 e 24.9.

Reflexão: por que no problema anterior temos que criar uma nova lista, e não podemos adicionar os dados de cada indivíduo à tupla?

In [289]:
altura_peso = [[1.80, 90], [1.65, 75], [1.91, 70]]

altura_peso_novo = []
posicao = 0
a = 0
b = 0
imc = 0
vimc = ''
# seu código

while a < len(altura_peso):
    imc = altura_peso[a][1]/(altura_peso[a][0]**2)
    if imc < 18.5: 
        vimc = 'baixo'
    elif imc > 24.9:
        vimc = 'alto'
    else:
        vimc = 'normal'
 
    altura_peso[a].append(imc)
    altura_peso[a].append(vimc)
    
    a += 1     

print(altura_peso)


[[1.8, 90, 27.777777777777775, 'alto'], [1.65, 75, 27.548209366391188, 'alto'], [1.91, 70, 19.188070502453332, 'normal']]
